version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Running build..."
      - ls
      - echo "Hello World"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
